dut-console: Add support for kdmx (kgdb) muxing
When cpudbg is selected, start kdmx in the background, so that we
can get both console and kgdb.

BUG=none
TEST=dut-console cpudbg

Change-Id: Idaae393416016dd859a4a67a3f714fdf28e42103
Reviewed-on: https://chromium-review.googlesource.com/1189527
Commit-Ready: Nicolas Boichat <drinkcat@chromium.org>
Tested-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>

diff --git a/contrib/dut-console b/contrib/dut-console
--- a/contrib/dut-console
+++ b/contrib/dut-console
@@ -16,9 +16,21 @@
 # The script also allows to connect to different servod port, e.g.
 # dut-control cpu 9999
 
+set -e
+
 # Script is stored in $CROS_SDK/src/platform/dev/contrib
 CROS_SDK="$(readlink -f "$(dirname "$0")/../../../..")"
 PYTHONPATH="${CROS_SDK}/chroot/usr/lib64/python2.7/site-packages"
+
+kdmx_pid=
+
+cleanup() {
+  trap - INT TERM ERR EXIT
+
+  if [[ -n "${kdmx_pid}" ]]; then
+    kill "${kdmx_pid}" 2>/dev/null
+  fi
+}
 
 get_pty() {
   local pty_name="$1"
@@ -49,7 +61,7 @@ dut-control type [port]
 Opens CPU/EC servo console using "cu", outputs to both terminal, and an output
 file named "log-\${type}[-\${port}]" in the current directory.
 
-  type      One of cpu, ec, cr50, fpmcu, servo, servo_v4
+  type      One of cpu, cpudbg, ec, cr50, fpmcu, servo, servo_v4
   [port]    servod port (optional, uses default if not specified)
 EOF
   exit 2
@@ -58,15 +70,22 @@ EOF
 main() {
   local type="$1"
   local port="$2"
+  local kdmx
   local pty
   local pty_name
   local outlog
 
   find_cu
 
+  trap cleanup INT TERM ERR EXIT
+
   case "${type}" in
   cpu)
     pty_name=cpu_uart_pty
+    ;;
+  cpudbg)
+    pty_name=cpu_uart_pty
+    kdmx='y'
     ;;
   ec)
     pty_name=ec_uart_pty
@@ -99,6 +118,45 @@ main() {
 
   if [[ -n "${port}" ]]; then
     outlog="${outlog}-${port}"
+  fi
+
+  if [[ "${kdmx}" == 'y' ]]; then
+    if ! hash kdmx; then
+      echo "Please build and put kdmx in your PATH first." >&2
+      echo "See https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/kernel-faq" >&2
+      exit 1
+    fi
+
+    # Note that we hardcode kdmx pty file location in the /tmp directory of the
+    # chroot. This should be ok as there is normally only one user, and only
+    # a single instance of dut-console/kdmx can run per console/servod instance.
+    local spath_in="/tmp/kdmx_${type}"
+    if [[ -n "${port}" ]]; then
+      spath_in="${spath_in}_${port}"
+    fi
+    local spath="${CROS_SDK}/chroot${spath_in}"
+    local spath_pty="${spath}_trm"
+    local spath_log="${spath}_log"
+
+    # Make sure we do not use a stale pty file
+    rm -f "${spath_pty}"
+
+    echo "Muxing ${pty_name}:${pty} with kdmx..."
+    kdmx -n -p "${pty}" -s "${spath}" > "${spath_log}" 2>&1 &
+    kdmx_pid="$!"
+    # Give kdmx enough time to start and create pty file
+    sleep 0.5
+
+    pty="$(cat "${spath_pty}" 2>/dev/null || true)"
+    if [[ -z "${pty}" ]]; then
+      echo "kdmx failed to start:" >&2
+      cat "${spath_log}" >&2
+      exit 1
+    fi
+    echo "You can now use kdbg inside the chroot with a command like:"
+    echo '${CROSS_ARCH}-gdb \
+        /build/${BOARD}/usr/lib/debug/boot/vmlinux \
+        -ex "target remote $(cat '"${spath_in}"'_gdb)'
   fi
 
   echo "Opening ${pty_name}:${pty}..."
