merge-kernel: Add retry for git push as workaround for GoB LOCK_FAILURE
Error looks like this:

remote: stack_entries: "  CREATE:\
0000000000000000000000000000000000000000\
8f63ac12d12949a10f2c633c5f1889db3aae3598 refs/changes/96/3450396/2\
(REJECTED_OTHER_REASON: transaction aborted)"

remote: stack_entries: "  CREATE:\
0000000000000000000000000000000000000000\
ae3f792fd619eec258bcb7ddc66d32a59b31b496\
refs/cache-automerge/8f/63ac12d12949a10f2c633c5f1889db3aae3598\
(LOCK_FAILURE)"

remote: stack_entries: "  UPDATE:\
8a4e60841a9db0fdca9241a1aefd6aa409d4f939\
3ce05252b8e398e4776c01fcbbff558ec0f4189b refs/changes/96/3450396/meta\
(REJECTED_OTHER_REASON: transaction aborted)"

Re-running the merge-kernel script does not work, maybe because it
has less work to do when re-using the same objects it avoids the bug
(noticable because the 2nd try of git push is much quicker).
Adding a single retry in the script seems to always work. I tried
adding 10 second sleep before the git push and that did not help.

TEST=several merge-kernel tries.
BUG=b:209031134

Change-Id: I1209eb913b5413564c9343e41768bd44a7c30b1f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/dev-util/+/3531165
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: William K Lin <wklin@google.com>
Commit-Queue: Martin Faltesek <mfaltesek@google.com>
Tested-by: Martin Faltesek <mfaltesek@google.com>
Auto-Submit: Martin Faltesek <mfaltesek@google.com>

diff --git a/contrib/merge-kernel b/contrib/merge-kernel
--- a/contrib/merge-kernel
+++ b/contrib/merge-kernel
@@ -1001,11 +1001,17 @@ do_upload() {
   if [[ ${upload} -ne 0 ]]; then
     if [[ "${bypass}" -eq 0 ]]; then
       if ! git push --no-verify ${dryrun} "${chromeos}" "${mbranch}:refs/for/${cbranch}%${options}"; then
-        error "Failed to upload changes into '${chromeos}'."
-        error "If the error is a validation error, and if your changes did not cause the problem,"
-        error "repeat the command with '-F' option. Do not use that option unless you are sure"
-        error "that your changes did not cause the problem."
-        die
+	# Due to unresolved GoB LOCK_FAILURE, a failure here is often b/209031134. A retry will
+	# workaround this. Can remove this extra retry when the bug is resolved.
+	if ! git push --no-verify ${dryrun} "${chromeos}" "${mbranch}:refs/for/${cbranch}%${options}"; then
+          error "Failed to upload changes into '${chromeos}'."
+          error "If the error is a validation error, and if your changes did not cause the problem,"
+          error "repeat the command with '-F' option. Do not use that option unless you are sure"
+          error "that your changes did not cause the problem."
+          die
+	fi
+	error "git push retry succeeded. If error messages during first try indicate GoB LOCK_FAILURE,"
+	error "please add cc to b/209031134 for signal boost."
       fi
     else
       if ! git push -o "uploadvalidator~skip" --no-verify ${dryrun} "${chromeos}" \
