update_program_fw: Fix wrong variable reference
Fix the incorrect variable reference to the project.

BUG=b:254170609
TEST=Run update with nivviks & nereid

Change-Id: I1e8beb932cb119254681cf12128c8cb829e2d469
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/dev-util/+/3980914
Auto-Submit: Andrew McRae <amcrae@google.com>
Tested-by: Andrew McRae <amcrae@google.com>
Commit-Queue: Sam McNally <sammc@chromium.org>
Reviewed-by: Sam McNally <sammc@chromium.org>
Commit-Queue: Andrew McRae <amcrae@google.com>

diff --git a/contrib/update_program_fw b/contrib/update_program_fw
--- a/contrib/update_program_fw
+++ b/contrib/update_program_fw
@@ -640,8 +640,9 @@ EOF
     PROJ_DIRS+=("${PDIR}")
   fi
   cd "${DEVCONTRIB}"
-  if ! (./cros_update_firmware -q "--board=${FLAGS_board}" "--project=${P}" "--project_srcuris" "--noappend_srcuris"); then
-    abort "cros_update_firmware failed for ${FLAGS_board} project ${P}"
+  echo "Updating firmware for project ${PROJ}"
+  if ! (./cros_update_firmware -q "--board=${FLAGS_board}" "--project=${PROJ}" "--project_srcuris" "--noappend_srcuris"); then
+    abort "cros_update_firmware failed for ${FLAGS_board} project ${PROJ}"
   fi
 done
 #
