stateful_update retry once on downloading error.
Sometimes wget may fail to get the full contents of stateful.tgz
and then tar will exit with code 2.

This CL retries wget and tar once to make it more robust
on dealing with network flake.

TEST=Run a trybot. Manually ran the script, force the branch to trigger.
BUG=chromium:485197;chromium:546630

Change-Id: Ic3af01ddc0639b75f4685b1c1d287c858b944494
Reviewed-on: https://chromium-review.googlesource.com/310922
Reviewed-by: Fang Deng <fdeng@chromium.org>
Tested-by: Fang Deng <fdeng@chromium.org>

diff --git a/stateful_update b/stateful_update
--- a/stateful_update
+++ b/stateful_update
@@ -39,6 +39,12 @@ remove_quotes() {
   echo "$1" | sed -e "s/^'//; s/'$//"
 }
 
+download_stateful_payload(){
+  # Download and unzip directories onto the stateful partition.
+  eval "wget -qS -T 300 -O - \"${stateful_update_url}\"" |
+      tar --ignore-command-error --overwrite --directory=${STATEFUL_DIR} -xz
+}
+
 update_dev_image () {
   local base_update_url devserver_url
   local local_payload_path
@@ -62,17 +68,32 @@ update_dev_image () {
     base_update_url="${devserver_url}/static"
   # Determine whether the path is local.
   elif [ -f "${path}" ] || [ "${path}" = "-" ]; then
-   local_payload_path=${path}
+    local_payload_path=${path}
   else
-   base_update_url=${path}
+    base_update_url=${path}
   fi
 
   if [ -n "${base_update_url}" ]; then
     local stateful_update_url="${base_update_url}/stateful.tgz"
-    echo >&2 "Downloading stateful payload from ${stateful_update_url}"
-    # Download and unzip directories onto the stateful partition.
-    eval "wget -qS -T 300 -O - \"${stateful_update_url}\"" |
-        tar --ignore-command-error --overwrite --directory=${STATEFUL_DIR} -xz
+    local download_exit_code=0
+    for i in `seq 1 2`; do
+      if [ $i -eq 1 ]; then
+        echo >&2 "Downloading stateful payload from ${stateful_update_url}"
+      else
+        echo >&2 "Downloading failed, retrying."
+      fi
+      if download_stateful_payload; then
+        download_exit_code=$?
+        echo >&2 "Downloading command returns code ${download_exit_code}."
+        break
+      else
+        download_exit_code=$?
+        echo >&2 "Downloading command returns code ${download_exit_code}."
+      fi
+    done
+    if [ ${download_exit_code} -ne 0 ]; then
+      return ${download_exit_code}
+    fi
     echo >&2 "Successfully downloaded update."
   else
     echo >&2 "Reading local payload ${local_payload_path}"
