cros_generate_update_payload: Stop umount busy retries.
Remove the retry loop present to clean up busy mount points created by
crbug.com/358933. Instead we are going to leave the directories alone,
and clean up them up after the build has compeleted.

BUG=chromium:358933
TEST=Manual payload genertion + cros flash to a device.

Change-Id: I150a40609e28a855dd7b5ba3d8c3df91bce48ec6
Reviewed-on: https://chromium-review.googlesource.com/220936
Reviewed-by: Gabe Black <gabeblack@chromium.org>
Commit-Queue: Don Garrett <dgarrett@chromium.org>
Tested-by: Don Garrett <dgarrett@chromium.org>

diff --git a/host/cros_generate_update_payload b/host/cros_generate_update_payload
--- a/host/cros_generate_update_payload
+++ b/host/cros_generate_update_payload
@@ -38,6 +38,12 @@ find_common_sh
 . "./chromeos-common.sh" || \
   die "Unable to load /usr/lib/installer/chromeos-common.sh"
 
+# We use this directory to create mount points as a way around crbug.com/358933.
+# Use FLAGS_work_dir instead when that workaround is no longer needed.
+# When that bug affects us, we will leak temp directories. They should
+# be cleaned up on the build servers at the end of cbuildbot.
+MOUNTS_ROOT="/tmp/crbug_358933"
+
 SRC_MNT=""
 DST_MNT=""
 SRC_KERNEL=""
@@ -47,7 +53,7 @@ DST_ROOT=""
 STATE_MNT=""
 
 # umount a loopback device, and remove the mount point.
-# This can be called normally (set -e), or during cleanup (set +3).
+# This can be called normally (set -e), or during cleanup (set +e).
 umount_and_rmdir() {
   local mnt_point="$1"
 
@@ -58,30 +64,18 @@ umount_and_rmdir() {
     return 0
   fi
 
+  sudo umount -v "$mnt_point" || return 1
+  sudo rmdir -v "$mnt_point" || rmdir_ret=$?
+  if [[ ${rmdir_ret} -ne 0 ]]; then
+    warn "sudo rmdir -v ${mnt_point} exited with: $rmdir_ret"
+    warn "Please note this failure in crbug.com/358933"
+  fi
 
-  for x in {1..30}; do
-    umount_ret=0
-    sudo umount -v "$mnt_point" || umount_ret=$?
-    if [ ${umount_ret} -ne 0 ]; then
-      warn "sudo umount -vl ${mnt_point} exited with: $umount_ret"
-      warn "Please note this failure in crbug.com/358933"
-    fi
+  # If the rmdir fails, we still return success and keep going. This punts
+  # failures up the chain of cleanup code, and makes them responsible for
+  # crbug.com/358933.
 
-    rmdir_ret=0
-    sudo rmdir -v "$mnt_point" || rmdir_ret=$?
-    if [ ${rmdir_ret} -eq 0 ]; then
-      # This means we worked!
-      return 0
-    else
-      warn "sudo rmdir -v ${mnt_point} exited with: $rmdir_ret"
-      warn "Please note this failure in crbug.com/358933"
-    fi
-
-    sleep 60
-    warn "Retrying umount_and_rmdir ${mnt_point}"
-  done
-
-  return 1
+  return 0
 }
 
 # Pass any argument to this method during normal cleanup.
@@ -164,7 +158,7 @@ patch_kernel() {
   local offset
   offset=$(partoffset "${IMAGE}" 1)
   : $(( offset *= 512 ))
-  STATE_MNT=$(mktemp -d --tmpdir="${FLAGS_work_dir}" state.XXXXXX)
+  STATE_MNT=$(mktemp -d --tmpdir="${MOUNTS_ROOT}" state.XXXXXX)
   sudo mount -o ro,loop,offset=$offset "$IMAGE" "$STATE_MNT"
   dd if="$STATE_MNT"/vmlinuz_hd.vblock of="$KERN_FILE" conv=notrunc 2>/dev/null
   umount_and_rmdir "$STATE_MNT"
@@ -240,6 +234,8 @@ eval set -- "${FLAGS_ARGV}"
 
 set -e
 
+mkdir -p "${MOUNTS_ROOT}"
+
 if [ -n "$FLAGS_src_image" ] && \
    [ "$FLAGS_outside_chroot" -eq "$FLAGS_FALSE" ]; then
   # We need to be in the chroot for generating delta images.
@@ -302,7 +298,7 @@ fi
 DST_KERNEL=$(extract_kern "$FLAGS_image" "$FLAGS_kern_path")
 DST_ROOT=$(extract_root "$FLAGS_image" "$FLAGS_root_path")
 
-DST_MNT=$(mktemp -d --tmpdir="${FLAGS_work_dir}" src_root.XXXXXX)
+DST_MNT=$(mktemp -d --tmpdir="${MOUNTS_ROOT}" dst_root.XXXXXX)
 sudo mount -o loop,ro "$DST_ROOT" "$DST_MNT"
 
 source "$DST_MNT"/usr/sbin/write_gpt.sh || warn "Could not read write_gpt.sh"
@@ -316,7 +312,7 @@ else
 fi
 
 if [ "$DELTA" -eq "$FLAGS_TRUE" ]; then
-  SRC_MNT=$(mktemp -d --tmpdir="${FLAGS_work_dir}" src_root.XXXXXX)
+  SRC_MNT=$(mktemp -d --tmpdir="${MOUNTS_ROOT}" src_root.XXXXXX)
   sudo mount -o loop,ro "$SRC_ROOT" "$SRC_MNT"
 
   # Preserve the path during sudo so that unpacked binaries are used when
