cros_chrome_make: add error message when ebuild invocation fails.
BUG=chromium-os:36711
TEST=ran manually

Change-Id: Ic55692bed5c41eabd79978843ace445e65553c94
Reviewed-on: https://gerrit.chromium.org/gerrit/38832
Reviewed-by: asharif <asharif@google.com>
Reviewed-by: David James <davidjames@chromium.org>
Commit-Ready: Ryan Cui <rcui@chromium.org>
Tested-by: Ryan Cui <rcui@chromium.org>

diff --git a/host/cros_chrome_make b/host/cros_chrome_make
--- a/host/cros_chrome_make
+++ b/host/cros_chrome_make
@@ -195,7 +195,8 @@ fi
 
 eval "USE='${use} -verbose ${runhooks}'" CCACHE_SIZE=2G \
      "FEATURES='${FEATURES} ${ccache}'" "CHROME_ORIGIN='${CHROME_ORIGIN}'" \
-     "${EBUILDCMD}" "${pkgfile}" "${ebuild_actions}"
+     "${EBUILDCMD}" "${pkgfile}" "${ebuild_actions}" \
+     || die "Failed to execute the ebuild."
 
 # If we didn't get to run hooks, don't update our cache.
 if [ -e "${workpath}/.prepared" ]; then
