cros_generate_update_payload: Retry umount after patch_kernel.
Use the umount loop after we finish doing the patch_kernel method. Also, adjust
the umount loop to be usable when running with set -e.

BUG=chromium:353558
TEST=Manual payload generation + trybot.

Change-Id: I4f88e353c0ec94c3bf3bf2acb406a88d3b59e1e9
Reviewed-on: https://chromium-review.googlesource.com/192420
Tested-by: Don Garrett <dgarrett@chromium.org>
Reviewed-by: David James <davidjames@chromium.org>
Commit-Queue: Don Garrett <dgarrett@chromium.org>

diff --git a/host/cros_generate_update_payload b/host/cros_generate_update_payload
--- a/host/cros_generate_update_payload
+++ b/host/cros_generate_update_payload
@@ -77,30 +77,34 @@ dump_umount_diags() {
   echo
 }
 
+# umount a loopback device, and remove the mount point.
+# This can be called normally (set -e), or during cleanup (set +3).
 umount_and_rmdir() {
   local mnt_point="$1"
 
-  local ret
+  local umount_ret
+  local rmdir_ret=0
 
   if [[ ! -d  "$mnt_point" ]]; then
     return 0
   fi
 
+
   for x in {1..30}; do
-    sudo umount -v "$mnt_point"
-    ret=$?
-    if [ ${ret} -ne 0 ]; then
-      echo "sudo umount -vl ${mnt_point} exited with: $ret"
+    umount_ret=0
+    sudo umount -v "$mnt_point" || umount_ret=$?
+    if [ ${umount_ret} -ne 0 ]; then
+      echo "sudo umount -vl ${mnt_point} exited with: $umount_ret"
       dump_umount_diags "${mnt_point}"
     fi
 
-    sudo rmdir -v "$mnt_point"
-    ret=$?
-    if [ ${ret} -eq 0 ]; then
+    rmdir_ret=0
+    sudo rmdir -v "$mnt_point" || rmdir_ret=$?
+    if [ ${rmdir_ret} -eq 0 ]; then
       # This means we worked!
       return 0
     else
-      echo "sudo rmdir -v ${mnt_point} exited with: $ret"
+      echo "sudo rmdir -v ${mnt_point} exited with: $rmdir_ret"
       dump_umount_diags "${mnt_point}"
     fi
 
@@ -196,8 +200,7 @@ patch_kernel() {
   STATE_MNT=$(mktemp -d --tmpdir="${FLAGS_work_dir}" state.XXXXXX)
   sudo mount -o ro,loop,offset=$offset "$IMAGE" "$STATE_MNT"
   dd if="$STATE_MNT"/vmlinuz_hd.vblock of="$KERN_FILE" conv=notrunc 2>/dev/null
-  sudo umount "$STATE_MNT"
-  rmdir "$STATE_MNT"
+  umount_and_rmdir "$SRC_MNT"
   STATE_MNT=""
 }
 
