cros_workon_make: support '.' for the project name
Handy extension which allows you to run cros_workon_make in any
directory and have it do the right thing.

The lame part is that you have to setup the mapping from git
project to ebuild yourself. I could do it dynamically but it would be
super slow.

BUG=none
TEST=Tested with and without workon.pkg set.

Change-Id: I7ba178032231ed93b89dca0755f1db414f83fa85
Reviewed-on: http://gerrit.chromium.org/gerrit/1970
Reviewed-by: Chris Masone <cmasone@chromium.org>
Tested-by: Mandeep Singh Baines <msb@chromium.org>

diff --git a/host/cros_workon_make b/host/cros_workon_make
--- a/host/cros_workon_make
+++ b/host/cros_workon_make
@@ -41,8 +41,15 @@ if [ -n "${FLAGS_board}" ]; then
   BOARD_KEYWORD="$(portageq-${FLAGS_board} envvar ARCH)"
 fi
 
+pkg="${1}"
+if [ "${pkg}" = "." ]; then
+  if ! pkg=$(git config workon.pkg); then
+    die "workon.pkg not set in git config for this project"
+  fi
+fi
+
 unstable_suffix="9999"
-workon_name="${1}-${unstable_suffix}"
+workon_name="${pkg}-${unstable_suffix}"
 pkgfile=
 workpath=
 
@@ -50,9 +57,9 @@ workpath=
 if ! pkgfile=$("${EQUERYCMD}" which "${workon_name}" 2> /dev/null); then
   if ACCEPT_KEYWORDS="~${BOARD_KEYWORD}" "${EQUERYCMD}" which "${workon_name}" \
       > /dev/null 2>&1; then
-    die "run 'cros_workon --board ${BOARD_STR} start ${1}' first!" 1>&2
+    die "run 'cros_workon --board ${BOARD_STR} start ${pkg}' first!" 1>&2
   fi
-  die "error looking up package $1"
+  die "error looking up package ${pkg}"
 fi
 
 if [ "${FLAGS_scrub}" = "${FLAGS_TRUE}" ]; then
@@ -94,7 +101,7 @@ fi
 
 if [ "${FLAGS_install}" = "${FLAGS_TRUE}" ]; then
   SANDBOX_WRITE=~/trunk CROS_WORKON_INPLACE=1 \
-    FEATURES="${emerge_features} ${FEATURES}" "${EMERGECMD}" "${1}"
+    FEATURES="${emerge_features} ${FEATURES}" "${EMERGECMD}" "${pkg}"
   exit $?
 fi
 
