quick-provision: Remove tmpdir if postinst fails
BUG=chromium:788473
TEST=repeat 20 autotest/files/contrib/loadtest.py $DS config.json --simultaneous 100 --total 2000
Change-Id: I3968dc3dfcb2faba7739cdc6362e203bb8b6fc0c
Reviewed-on: https://chromium-review.googlesource.com/804963
Commit-Ready: David Riley <davidriley@chromium.org>
Tested-by: David Riley <davidriley@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>

diff --git a/quick-provision/quick-provision b/quick-provision/quick-provision
--- a/quick-provision/quick-provision
+++ b/quick-provision/quick-provision
@@ -198,9 +198,13 @@ set_next_kernel() {
   info "Update next kernel to try (via postinst)"
   local tmpmnt="$(mktemp -d)"
   mount -o ro "${NEXT_ROOT}" "${tmpmnt}" || die "Unable to mount ${NEXT_ROOT}."
-  "${tmpmnt}/postinst" "${NEXT_ROOT}" || die "postinst failed."
+  "${tmpmnt}/postinst" "${NEXT_ROOT}"
+  local retval="$?"
   umount "${tmpmnt}"
   rmdir "${tmpmnt}"
+  if [[ "${retval}" -ne "0" ]]; then
+    die "postinst failed."
+  fi
 }
 
 main() {
